[[plugins]]
repo = 'Shougo/dein.vim'

# 自動補完
[[plugins]]
repo = 'Townk/vim-autoclose'

# 補完ruby
[[plugins]]
repo = 'tpope/vim-endwise'

# color
[[plugins]]                  
repo = 'joshdick/onedark.vim'
hook_add = '''       
  colorscheme onedark
'''    

# Linter
[[plugins]]
repo = 'w0rp/ale'

# Git
[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
  source ~/.config/nvim/plugins/gitgutter.vim
'''

[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = '''
  source ~/.config/nvim/plugins/fugitive.vim
'''

# ファイラ
[[plugins]]
repo = 'Shougo/defx.nvim'
hook_add = '''
  source ~/.config/nvim/plugins/defx.vim
'''
